### ISSUE TITLE
Is plugin ready?

### ISSUE THREAD

**Issue by frozt** [hayzem/woocommerce-iyzico-plugin#1]
Hi, As I have checked the code some files doesn't exist, which are:

\Iyzipay\Request\CreateSubMerchantRequest
\Iyzipay\Model\SubMerchantType
\Iyzipay\Model\SubMerchant

These new models and requests need to be implemented within existing structure for the plugin at least work with basic functionality, is it correct?

**Comment by hayzem** [comment]
This repo has not been maintained or updated to it's working version for long time. Probably it's correct. 
I worked on it when the plugin didn't have subMerchant support. I don't know if the main repo has that feature already.

**Comment by frozt** [comment]
Thanks for quick reply. The main plugin still doesn't have submerchant support. If I implement those parts, I will contribute to the repo also.

**Comment by hayzem** [comment]
Awesome. I will check the working version of mine and update the repo.
